service: java-jasperreport

frameworkVersion: "3.20.0"

provider:
  name: aws
  endpointType: REGIONAL
  runtime: java11
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: jrxml-templates-jasperreport
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - "secretsmanager:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - "rds:*"
          Resource: "*"

package:
  individually: true
  patterns:
    - "./**"

custom:
  DB_NAME: ExampleDB
  USERNAME: master
  PASSWORD: password
  MYSQL:
    HOST:
      Fn::GetAtt: [MySqlRDSInstance, Endpoint.Address]
    PORT:
      Fn::GetAtt: [MySqlRDSInstance, Endpoint.Port]
    VPC_CIDR: 173

functions:
  LambdaJasperReport:
    handler: btg.reporteria.LambdaFunctionHandler
    name: LambdaJasperReport
    memorySize: 512
    timeout: 60
    package:
      artifact: target/btgfx-1.0.jar
    environment:
      RDS_DB_DRIVER: "org.mariadb.jdbc.Driver"
      BUCKET_NAME: "jrxml-templates-jasperreport"
      SECRET_NAME: "secret-jasperdb-1"
      SECRET_REGION: "us-east-1"
    vpc:
      securityGroupIds:
        - Ref: JasperLambdaSecurityGroup
      subnetIds:
        - Ref: JasperLambdaPrivateSubnet
    events:
      - http:
          path: /reports
          method: get
          request:
            parameters:
              querystrings:
                ordeCodigo: true

resources:
  Resources:
    EIP: ${file(./resource/EIP.yml)}
    JasperLambdaInternetGateway: ${file(./resource/JasperLambdaInternetGateway.yml)}
    JasperLambdaInternetGatewayRoute: ${file(./resource/JasperLambdaInternetGatewayRoute.yml)}
    JasperLambdaNATGateway: ${file(./resource/JasperLambdaNATGateway.yml)}
    JasperLambdaNATGatewayRoute: ${file(./resource/JasperLambdaNATGatewayRoute.yml)}
    JasperLambdaSecurityGroup: ${file(./resource/JasperLambdaSecurityGroup.yml)}
    JasperLambdaSecurityGroupIngress: ${file(./resource/JasperLambdaSecurityGroupIngress.yml)}
    JasperLambdaSubnetGroup: ${file(./resource/JasperLambdaSubnetGroup.yml)}
    JasperLambdaVPC: ${file(./resource/JasperLambdaVPC.yml)}
    JasperLambdaVPCGA: ${file(./resource/JasperLambdaVPCGA.yml)}
    JasperLambdaPrivateRouteTable: ${file(./resource/JasperLambdaPrivateRouteTable.yml)}
    JasperLambdaPrivateSubnet: ${file(./resource/JasperLambdaPrivateSubnet.yml)}
    JasperLambdaPrivateSubnetRouteTableAssociation: ${file(./resource/JasperLambdaPrivateSubnetRouteTableAssociation.yml)}
    JasperLambdaPublicRouteTable: ${file(./resource/JasperLambdaPublicRouteTable.yml)}
    JasperLambdaPublicSubnet: ${file(./resource/JasperLambdaPublicSubnet.yml)}
    JasperLambdaPublicSubnetRouteTableAssociation: ${file(./resource/JasperLambdaPublicSubnetRouteTableAssociation.yml)}
    MySqlRDSInstance: ${file(./resource/MySqlRDSInstance.yml)}
