service: java-jasperreport

frameworkVersion: "3.19.0"

provider:
  name: aws
  endpointType: REGIONAL
  runtime: java11
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: jrxml-templates-jasperreport
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - "secretsmanager:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - "rds:*"
          Resource: "*"

custom:
  DB_NAME: ExampleDB
  USERNAME: master
  PASSWORD: password
  MYSQL:
    HOST:
      Fn::GetAtt: [MySqlRDSInstance, Endpoint.Address]
    PORT:
      Fn::GetAtt: [MySqlRDSInstance, Endpoint.Port]
    VPC_CIDR: 10

package:
  artifact: target/btgfx-1.0.jar

functions:
  LambdaJasperReport:
    handler: btg.reporteria.LambdaFunctionHandler
    name: LambdaJasperReport
    memorySize: 512
    timeout: 60
    environment:
      RDS_DB_DRIVER: "org.mariadb.jdbc.Driver"
      BUCKET_NAME: "jrxml-templates-jasperreport"
      SECRET_NAME: "secret-jasperdb-1"
      SECRET_REGION: "us-east-1"
    vpc:
      securityGroupIds:
        - Ref: ServerlessSecurityGroup
      subnetIds:
        - Ref: ServerlessSubnetA
    events:
      - http:
          path: /reports
          method: get
          request:
            parameters:
              querystrings:
                ordeCodigo: true

resources:
  Resources:
    ServerlessInternetGateway: ${file(./resource/ServerlessInternetGateway.yml)}
    ServerlessVPC: ${file(./resource/ServerlessVPC.yml)}
    ServerlessVPCGA: ${file(./resource/ServerlessVPCGA.yml)}
    ServerlessSubnetA: ${file(./resource/ServerlessSubnetA.yml)}
    ServerlessSubnetB: ${file(./resource/ServerlessSubnetB.yml)}
    ServerlessSubnetGroup: ${file(./resource/ServerlessSubnetGroup.yml)}
    ServerlessSecurityGroup: ${file(./resource/ServerlessSecurityGroup.yml)}
    RouteTablePublic: ${file(./resource/RouteTablePublic.yml)}
    RoutePublic: ${file(./resource/RoutePublic.yml)}
    RouteTableAssociationSubnetA: ${file(./resource/RouteTableAssociationSubnetA.yml)}
    RouteTableAssociationSubnetB: ${file(./resource/RouteTableAssociationSubnetB.yml)}

    MySqlRDSInstance: ${file(./resource/MySqlRDSInstance.yml)}
